project_setup:
  seed: 42
  device: "cpu"
  num_threads: 4

data:
  chunk_size: 300
  chunk_overlap: 50

models:
  dense_embedder: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  reranker: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  # reader_qa: "letrunglinh/qa_pnc"
  reader_qa: "models/qwen2.5-3b-instruct-q4_k_m.gguf"

hyperparameters:
  hybrid_alpha: 0.5
  top_k_hybrid: 5      
  top_k_rerank: 0
  max_new_tokens: 150
  use_reranker: false   